[deploy]
startCommand = "npm run db:migrate:deploy; echo '=== MIGRATE DONE, EXIT=$?' && echo '=== STARTING NODE ===' && node --version && ls -la .next/standalone/ && node .next/standalone/server.js"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
