[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run db:migrate:deploy && npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
